language: perl

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
    - os: linux
      sudo: required
      services: docker
      env: OBERTH_COVERAGE=coveralls
    - os: osx

before_install:
  - eval "$(curl https://raw.githubusercontent.com/oberth-manoeuvre/oberth-prototype/master/script/ci/travis-oberth.sh)"
  - ( cd "$OBERTH_PROTOTYPE_DIR"/vendor/p5-Oberth-Launch && git checkout $TRAVIS_COMMIT )
  - travis-oberth before-install

install: travis-oberth install
script:  travis-oberth script
