language: perl

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
    - os: linux
      sudo: required
      services: docker
      env: OBERTH_COVERAGE=coveralls
    - os: osx

before_install:
  - eval "$(curl https://raw.githubusercontent.com/oberth-manoeuvre/oberth-prototype/master/script/ci/travis-oberth.sh)"
  - ( [[ -n "$TRAVIS_PULL_REQUEST_SHA" ]] && COMMIT=$TRAVIS_PULL_REQUEST_SHA || COMMIT=$TRAVIS_COMMIT ; cd "$OBERTH_PROTOTYPE_DIR"/vendor/p5-Oberth-Launch && git remote add travis $TRAVIS_BUILD_DIR && git fetch travis && git checkout $COMMIT )
  - travis-oberth before-install

install: travis-oberth install
script:  travis-oberth script
