language: perl

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      services: docker
    - os: linux
      sudo: required
      services: docker
      env: ORBITAL_COVERAGE=coveralls
    - os: osx
  allow_failures:
    - os: linux
      sudo: required
      services: docker
      env: ORBITAL_COVERAGE=coveralls

before_install:
  - eval "$(curl https://raw.githubusercontent.com/orbital-transfer/launch-site/master/script/ci/travis-orbital.sh)"
  - ( [[ -n "$TRAVIS_PULL_REQUEST_SHA" ]] && COMMIT=$TRAVIS_PULL_REQUEST_SHA || COMMIT=$TRAVIS_COMMIT ; cd "$ORBITAL_LAUNCH_SITE_DIR"/vendor/p5-Orbital-Launch && git remote add travis $TRAVIS_BUILD_DIR && git fetch travis && git checkout $COMMIT )
  - travis-orbital before-install

install: travis-orbital install
script:  travis-orbital script
