version: 1.0.{build}

cache:
  # cache local::lib
  - C:\msys64\mingw64\lib\perl5\site_perl -> appveyor.yml
  - C:\msys64\mingw64\bin\site_perl -> appveyor.yml
  - C:\msys64\home\%Username%\perl5 -> appveyor.yml
  - maint/cpanfile-git-log -> appveyor.yml
  # cache for devops helper.pl
  - C:\Perl\site -> appveyor.yml

install:
  - ps: . { iwr -useb https://raw.githubusercontent.com/oberth-manoeuvre/oberth-prototype/master/script/ci/appveyor-oberth.ps1 } | iex
  - ps: |
      Push-Location
      if ( -Not ( [string]::IsNullOrEmpty($Env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT) ) ) { $Env:COMMIT=$Env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT } else { $Env:COMMIT=$Env:APPVEYOR_REPO_COMMIT }
      Write-Host "Using commit $Env:COMMIT"
      cd $Env:OBERTH_PROTOTYPE_DIR\vendor\p5-Oberth-Launch
      git remote add appveyor $Env:APPVEYOR_BUILD_FOLDER ; git fetch appveyor ; git checkout $Env:COMMIT
      Pop-Location
  - ps: |
      Push-Location
      cd $Env:OBERTH_PROTOTYPE_DIR\vendor-external\cpm
      git remote add oberth-manoeuvre https://github.com/oberth-manoeuvre/cpm.git ; git fetch oberth-manoeuvre ; git checkout oberth-manoeuvre/multi-worker-win32
      Pop-Location
  - ps: appveyor-oberth install

build_script:
  - ps: appveyor-oberth build-script
test_script:
  - ps: appveyor-oberth test-script
