version: 1.0.{build}

cache:
  # cache local::lib
  - C:\msys64\mingw64\lib\perl5\site_perl -> appveyor.yml
  - C:\msys64\mingw64\bin\site_perl -> appveyor.yml
  - C:\msys64\home\%Username%\perl5 -> appveyor.yml
  - maint/cpanfile-git-log -> appveyor.yml
  # cache for devops helper.pl
  - C:\Perl\site -> appveyor.yml

install:
  - ps: . { iwr -useb https://raw.githubusercontent.com/orbital-transfer/launch-site/master/script/ci/appveyor-orbital.ps1 } | iex
  - ps: |
      Push-Location
      if ( -Not ( [string]::IsNullOrEmpty($Env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT) ) ) { $Env:COMMIT=$Env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT } else { $Env:COMMIT=$Env:APPVEYOR_REPO_COMMIT }
      Write-Host "Using commit $Env:COMMIT"
      cd $Env:ORBITAL_LAUNCH_SITE_DIR\vendor\p5-Orbital-Launch
      git remote add appveyor $Env:APPVEYOR_BUILD_FOLDER ; git fetch appveyor ; git checkout $Env:COMMIT
      Pop-Location
  - ps: appveyor-orbital install

build_script:
  - ps: appveyor-orbital build-script
test_script:
  - ps: appveyor-orbital test-script
